### ISSUE TITLE
Hi - This example does not include REST example

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/SharePoint-Add-in-JSOM-CrossDomain#1]
Hi There, I have been searching EVERYWHERE for a decent provider hosted example using javascript REST.

If you have one, can you please forward this to me. If one does not exist, can you either create one or at least give me the info as to what I need to do on this.

I need a provider hosted app, to use the cross domain library to call into the host web, using javascript REST and not the csom.

For some reason, I have not been able to find this anywhere! crazy.

**Comment by Rick-Kirkham** [comment]
I think this sample is what you want: [SharePoint-Add-in-REST-OData-CrossDomain](https://github.com/OfficeDev/SharePoint-Add-in-REST-OData-CrossDomain)

**Comment by nigel-dewar** [comment]
Hi there. This example only shows how to access a lists data in the app web and not the hostweb. I need something that can access data in the host web. I have tried to do this but i with no luck.


Sent from Samsung Mobile


-------- Original message --------
From: Rick-Kirkham
Date:20/10/2016 03:38 (GMT+10:00)
To: OfficeDev/SharePoint-Add-in-JSOM-CrossDomain
Cc: nigel-dewar , Author
Subject: Re: [OfficeDev/SharePoint-Add-in-JSOM-CrossDomain] Hi - This example does not include REST example (#1)


I think this sample is what you want: SharePoint-Add-in-REST-OData-CrossDomain<https://github.com/OfficeDev/SharePoint-Add-in-REST-OData-CrossDomain>

-

**Comment by nigel-dewar** [comment]
I will post an example of what i mean soon.


Sent from Samsung Mobile


-------- Original message --------
From: Rick-Kirkham
Date:20/10/2016 03:38 (GMT+10:00)
To: OfficeDev/SharePoint-Add-in-JSOM-CrossDomain
Cc: nigel-dewar , Author
Subject: Re: [OfficeDev/SharePoint-Add-in-JSOM-CrossDomain] Hi - This example does not include REST example (#1)


I think this sample is what you want: SharePoint-Add-in-REST-OData-CrossDomain<https://github.com/OfficeDev/SharePoint-Add-in-REST-OData-CrossDomain>

-
